<?php
/**
 * This file is part of the Techworker\Uuid package.
 *
 * (c) Benjamin Ansbach <benjaminansbach@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Techworker\Uuid\ByteProvider\Random;

use Techworker\Uuid\ByteList;
use Techworker\Uuid\ByteProvider\ByteProviderInterface;

/**
 * This provider creates a 16 Byte sized ByteList with random values provided
 * by the mt_rand PHP function.
 *
 * @package    Techworker\Uuid
 * @subpackage ByteProvider
 * @author     Benjamin Ansbach <benjaminansbach@googlemail.com>
 * @copyright  2014 Benjamin Ansbach <benjaminansbach@googlemail.com>
 * @license    MIT
 * @link       http://www.techworker.de/
 * @see        http://www.ietf.org/rfc/rfc4122.txt
 */
class MtRand implements ByteProviderInterface
{
    /**
     * Returns the 16 randomly generated bytes.
     *
     * @return ByteList
     */
    public function provide()
    {
        $bytes = new ByteList(16);
        for($i = 0; $i < 16; $i++)
        {
            mt_srand();
            $bytes->add(mt_rand(0, 255));
        }

        return $bytes;
    }
}